version: 2

sources:
  - name: raw
    schema: public
    tables:
      - name: raw_olist_orders_dataset
      - name: raw_olist_customers_dataset
      - name: raw_olist_order_items_dataset
      - name: raw_superstore